version = 1
SPDX-PackageName = "cred-scan"
SPDX-PackageSupplier = "Outscale <opensource@outscale.com>"
SPDX-PackageDownloadLocation = "https://github.com/outscale/cred-scan/"

[[annotations]]
path = ["**.sh", "**.txt", "**.md", "**.yml", "**.yaml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Outscale SAS <opensource@outscale.com>"
SPDX-License-Identifier = "BSD-3-Clause"
